# kNN
## implemented by python library numpy  
this is a simple kNN implement to solve the digit-recognizatio(mnist dataset) problem.  
pandas is only used to load the dataset.

In [47]:
import numpy as np
import pandas as pd
import operator

here we use the kaggle competition-data recognization dataset.it has 28x28 = 784 features and 1 label for each training digit.  
and we split the origin train dataset as training data and cross-validation dataset.because we need to know our algorithm performed well or not.  
also I won't use the whole dataset,since it will build a huge matrix using kNN algorithm that our memory will leak.

In [11]:
#def loadDataSet(path='./data/train.csv'):
train = pd.read_csv('./data/train.csv')


In [13]:
train = train.iloc[:4200,:]

In [14]:
label = train.label.as_matrix()
train = train.drop('label',axis = 1).as_matrix()

In [18]:
def loadDataSet(path='./data/train.csv'):
    data = pd.read_csv(path)
    train = data.iloc[:4000,:]
    test = data.iloc[4000:4200,:]
    
    train_label = train.label.as_matrix()
    train = train.drop('label', axis=1).as_matrix()
    
    test_label = test.label.as_matrix()
    test = test.drop('label', axis=1).as_matrix()
    
    return train,train_label,test,test_label

In [32]:
train, train_label,test, test_label = loadDataSet()

In [50]:
pred_label = np.zeros((test_label.shape[0],1))

In [53]:
pred_label[0]

array([ 1.])

In [57]:
def kNN(k=5):
    train, train_label,test, test_label = loadDataSet()
    pred_label = np.zeros((test_label.shape[0],1))
    for i in range(test.shape[0]):
        data = test[i,:]
        distanceMatrix = np.tile(data, (train.shape[0], 1)) - train
        distanceMatrix = distanceMatrix**2
        distanceMatrix = distanceMatrix.sum(axis= 1)
        sortIndex = distanceMatrix.argsort()
        classCount = {}
        for j in range(k):
            voteLabel = train_label[sortIndex[j]]
            classCount[voteLabel] = classCount.get(voteLabel, 0) + 1
        sortedClassCount = sorted(classCount.iteritems(), key=operator.itemgetter(1),reverse=True)
        pred_label[i] = sortedClassCount[0][0]
        
    return pred_label

In [58]:
ans = kNN()

In [59]:
ans

array([[ 8.],
       [ 8.],
       [ 0.],
       [ 5.],
       [ 0.],
       [ 0.],
       [ 3.],
       [ 8.],
       [ 3.],
       [ 1.],
       [ 2.],
       [ 5.],
       [ 6.],
       [ 3.],
       [ 0.],
       [ 6.],
       [ 6.],
       [ 1.],
       [ 3.],
       [ 9.],
       [ 6.],
       [ 0.],
       [ 2.],
       [ 4.],
       [ 6.],
       [ 3.],
       [ 2.],
       [ 7.],
       [ 8.],
       [ 3.],
       [ 2.],
       [ 9.],
       [ 9.],
       [ 4.],
       [ 1.],
       [ 2.],
       [ 7.],
       [ 8.],
       [ 6.],
       [ 1.],
       [ 8.],
       [ 0.],
       [ 9.],
       [ 5.],
       [ 5.],
       [ 2.],
       [ 5.],
       [ 7.],
       [ 4.],
       [ 0.],
       [ 2.],
       [ 9.],
       [ 8.],
       [ 3.],
       [ 2.],
       [ 1.],
       [ 2.],
       [ 4.],
       [ 6.],
       [ 2.],
       [ 3.],
       [ 3.],
       [ 2.],
       [ 1.],
       [ 0.],
       [ 1.],
       [ 5.],
       [ 5.],
       [ 6.],
       [ 1.],
       [ 8.],
      

In [60]:
test_label

array([8, 8, 0, 5, 0, 0, 3, 8, 2, 1, 2, 5, 6, 3, 0, 6, 6, 1, 3, 9, 6, 0, 2,
       4, 6, 3, 2, 7, 8, 3, 2, 9, 9, 4, 7, 2, 7, 8, 6, 1, 5, 0, 9, 5, 5, 2,
       5, 7, 4, 0, 2, 9, 8, 3, 2, 1, 2, 4, 6, 2, 3, 3, 2, 1, 6, 8, 5, 5, 6,
       1, 8, 4, 4, 4, 7, 8, 1, 2, 0, 4, 5, 8, 2, 3, 4, 2, 7, 7, 9, 4, 7, 5,
       9, 5, 7, 0, 4, 0, 6, 8, 5, 8, 6, 0, 4, 3, 6, 2, 0, 9, 1, 4, 9, 7, 9,
       5, 6, 2, 2, 0, 8, 4, 2, 9, 9, 5, 9, 6, 9, 0, 4, 0, 9, 0, 6, 6, 8, 4,
       8, 7, 3, 1, 4, 9, 0, 1, 7, 0, 7, 7, 3, 3, 2, 4, 0, 9, 6, 1, 9, 2, 8,
       6, 5, 0, 2, 1, 7, 8, 0, 0, 8, 6, 1, 5, 4, 0, 6, 6, 9, 7, 7, 1, 0, 8,
       6, 3, 8, 5, 6, 0, 8, 7, 3, 2, 3, 4, 5, 9, 2, 5], dtype=int64)

In [65]:
test_label = test_label.reshape(200,1)

In [66]:
ans == test_label

array([[ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [

In [67]:
hit = ans == test_label

183

In [68]:
acc = hit.sum() * 1.0/test_label.shape[0]

In [69]:
acc

0.91500000000000004